!	poncts	!
!!	poncts	!!!
!!!	poncts	!!!
!?	poncts	!?
!?!?	poncts	!?
"	''	"
"	``	"
"	ponctw	"
$	$	$
%	NN	%
&	V	&
&lt;-	poncts	<-
'	''	'
'	V	'
'	``	'
''	''	''
'Alf	N	'Alf
'Ead	N	'Ead
'Ealth	N	'Ealth
'Ole	N	'Ole
'Ome	N	'Ome
'Ouse	N	'Ouse
'Yenas	N	'Yenas
'alf	N	'alf
'at	N	'at
'd	V	'd
'ead	N	'ead
'ealth	N	'ealth
'em	I	'em
'll	V	'll
'm	V	'm
'ole	N	'ole
'ome	N	'ome
'ouse	N	'ouse
're	V	're
's	V	's
've	V	've
'yenas	N	'yenas
(	parento	(
)	parentf	)
*	parentf	-
*	parento	-
*	ponctw	-
+	parentf	-
+	parento	-
+	ponctw	-
,	ponctw	,
-	,	-
-	parentf	-
-	parento	-
-	ponctw	-
-&gt;	poncts	->
--	,	--
--	:	--
---	,	---
->	poncts	->
-LRB-	-LRB-	-LRB-
-RRB-	-RRB-	-RRB-
.	poncts	.
...	ponctw	...
/	,	/
:	ponctw	:
;	ponctw	;
<-	poncts	<-
<<	-LRB-	<<
>>	-RRB-	>>
?	poncts	?
?!	poncts	!?
?!?!	poncts	!?
@	IN	@
A	Ns	A
A's	Np	A
A-bomb	Ns	A-bomb
A-bombs	Np	A-bomb
A-frame	Ns	A-frame
A-frames	Np	A-frame
AA	Ns	AA
AAS	Ns	AAS
AASes	Np	AAS
AAs	Np	AA
AB	Ns	AB
ABC	Ns	ABC
ABCs	Np	ABC
ABLS	Ns	ABLS
ABLSes	Np	ABLS
ABM	Ns	ABM
ABMs	Np	ABM
ABs	Np	AB
AC	Ns	AC
ACTH	Ns	ACTH
ACTHs	Np	ACTH
ACs	Np	AC
AD	Ns	AD
ADP	Ns	ADP
ADPs	Np	ADP
ADs	Np	AD
AEC	Ns	AEC
AECs	Np	AEC
AI	Ns	AI
AIDS	Ns	AIDS
AIDS_vaccine	Ns	AIDS_vaccine
AIDS_vaccines	Np	AIDS_vaccine
AIDSes	Np	AIDS
AIs	Np	AI
ALGOL	Ns	ALGOL
ALGOLs	Np	ALGOL
AM	Ns	AM
AMP	Ns	AMP
AMPs	Np	AMP
AMs	Np	AM
AMusD	Ns	AMusD
AMusDs	Np	AMusD
AN	Ns	AN
AND	Ns	AND
ANDes	Np	AND
ANs	Np	AN
APC	Ns	APC
APCs	Np	APC
ASAP	N	ASAP
ATM_machine	Ns	ATM_machine
ATM_machines	Np	ATM_machine
ATP	Ns	ATP
ATPs	Np	ATP
AU	Ns	AU
AUs	Np	AU
A_Special	Ns	A_Special
A_Specials	Np	A_Special
A_level	Ns	A_level
A_levels	Np	A_level
Aachen	Ns	Aachen
Aachens	Np	Aachen
Aaron	Ns	Aaron
Aaronic	Apos	Aaronic
Aaronicer	Acomp	Aaronic
Aaronicest	Asup	Aaronic
Aarons	Np	Aaron
Ab	Ns	Ab
Abbasid	Apos	Abbasid
Abbasid	Ns	Abbasid
Abbasider	Acomp	Abbasid
Abbasidest	Asup	Abbasid
Abbasids	Np	Abbasid
Abbevillian	Apos	Abbevillian
Abbevillian	Ns	Abbevillian
Abbevillianer	Acomp	Abbevillian
Abbevillianes	Np	Abbevillian
Abbevillianest	Asup	Abbevillian
Abel	Ns	Abel
Abels	Np	Abel
Aberdeen	Ns	Aberdeen
Aberdeens	Np	Aberdeen
Aberystwyth	Ns	Aberystwyth
Aberystwyths	Np	Aberystwyth
Abib	Ns	Abib
Abibs	Np	Abib
Abidjan	Ns	Abidjan
Abidjans	Np	Abidjan
Abietatineae	Ns	Abietatineae
Abietatineaees	Np	Abietatineae
Abitibi	N	Abitibi
Abitibi	Ns	Abitibi
Abitibis	Np	Abitibi
Abkhazia	Ns	Abkhazia
Abkhazian	Ns	Abkhazian
Abkhazians	Np	Abkhazian
Abkhazias	Np	Abkhazia
Abnaki	Ns	Abnaki
Abnakis	Np	Abnaki
Abo	Ns	Abo
Aboriginal	Ns	Aboriginal
Aboriginals	Np	Aboriginal
Aborigine	Ns	Aborigine
Aborigines	Np	Aborigine
Abos	Np	Abo
Abraham	Ns	Abraham
Abraham_Lincoln	Ns	Abraham_Lincoln
Abraham_Lincolns	Np	Abraham_Lincoln
Abrahams	Np	Abraham
Abrocomidae	Ns	Abrocomidae
Abrocomidaes	Np	Abrocomidae
Abruzzi	Ns	Abruzzi
Abruzzis	Np	Abruzzi
Abs	Np	Ab
Abuja	N	Abuja
Abuja	Ns	Abuja
Abujas	Np	Abuja
Abyssinia	Ns	Abyssinia
Abyssinian	Apos	Abyssinian
Abyssinian	Ns	Abyssinian
Abyssinianer	Acomp	Abyssinian
Abyssinianest	Asup	Abyssinian
Abyssinians	Np	Abyssinian
Abyssinias	Np	Abyssinia
Ac	Ns	Ac
Acadia	Ns	Acadia
Acadian	Apos	Acadian
Acadian	Ns	Acadian
Acadianer	Acomp	Acadian
Acadianest	Asup	Acadian
Acadians	Np	Acadian
Acadias	Np	Acadia
Acalephae	Ns	Acalephae
Acalephaes	Np	Acalephae
Acanthaceae	Ns	Acanthaceae
Acanthaceaees	Np	Acanthaceae
Acapulco	Ns	Acapulco
Acapulcoes	Np	Acapulco
Accadian	Ns	Accadian
Accadians	Np	Accadian
Accipitridae	Ns	Accipitridae
Accipitridaes	Np	Accipitridae
Accra	Ns	Accra
Accras	Np	Accra
Aceldama	Ns	Aceldama
Aceldamas	Np	Aceldama
Achaea	Ns	Achaea
Achaean	Apos	Achaean
Achaean	Ns	Achaean
Achaeaner	Acomp	Achaean
Achaeanest	Asup	Achaean
Achaeans	Np	Achaean
Achaeas	Np	Achaea
Achaemenid	Ns	Achaemenid
Achaemenids	Np	Achaemenid
Achaian	Apos	Achaian
Achaian	Ns	Achaian
Achaianer	Acomp	Achaian
Achaianest	Asup	Achaian
Achaians	Np	Achaian
Achates	Ns	Achates
Achatess	Np	Achates
Acheron	Ns	Acheron
Acherons	Np	Acheron
Acheulean	Apos	Acheulean
Acheulean	Ns	Acheulean
Acheuleaner	Acomp	Acheulean
Acheuleanes	Np	Acheulean
Acheuleanest	Asup	Acheulean
Acheulian	Apos	Acheulian
Acheulian	Ns	Acheulian
Acheulianer	Acomp	Acheulian
Acheulianes	Np	Acheulian
Acheulianest	Asup	Acheulian
Achillean	Apos	Achillean
Achilleaner	Acomp	Achillean
Achilleanest	Asup	Achillean
Achilles	Ns	Achilles
Achilles'_heel	Ns	Achilles'_heel
Achilles'_heels	Np	Achilles'_heel
Achilleses	Np	Achilles
Achromycin	Ns	Achromycin
Achromycins	Np	Achromycin
Aconcagua	Ns	Aconcagua
Aconcaguas	Np	Aconcagua
Acraeidae	Ns	Acraeidae
Acraeidaes	Np	Acraeidae
Acrania	Ns	Acrania
Acranias	Np	Acrania
Acrasiales	Ns	Acrasiales
Acrasialess	Np	Acrasiales
Acrididae	Ns	Acrididae
Acrididaes	Np	Acrididae
Acridiidae	Ns	Acridiidae
Acridiidaes	Np	Acridiidae
Acrilan	Ns	Acrilan
Acrilans	Np	Acrilan
Acropolis	Ns	Acropolis
Acropoliss	Np	Acropolis
Acrothoracica	Ns	Acrothoracica
Acrothoracicas	Np	Acrothoracica
Acs	Np	Ac
Actaea	Np	Actaeon
Actaeon	Ns	Actaeon
Actinaria	Ns	Actinaria
Actinariaes	Np	Actinaria
Actiniaria	Ns	Actiniaria
Actiniariaes	Np	Actiniaria
Actinomycetales	Ns	Actinomycetales
Actinomycetaless	Np	Actinomycetales
Actinophrys	Ns	Actinophrys
Actinophryses	Np	Actinophrys
Actinopoda	Ns	Actinopoda
Actinopodas	Np	Actinopoda
Actinopterygii	Ns	Actinopterygii
Actinopterygiis	Np	Actinopterygii
Actinozoa	Ns	Actinozoa
Actinozoas	Np	Actinozoa
Actium	Ns	Actium
Actiums	Np	Actium
Aculeata	Ns	Aculeata
Aculeatas	Np	Aculeata
Ada	Ns	Ada
Adalia	Ns	Adalia
Adalias	Np	Adalia
Adam	Ns	Adam
Adam's_apple	Ns	Adam's_apple
Adam's_apples	Np	Adam's_apple
Adamic	Apos	Adamic
Adamicallier	Rcomp	Adamically
Adamicalliest	Rsup	Adamically
Adamically	Rpos	Adamically
Adamicer	Acomp	Adamic
Adamicest	Asup	Adamic
Adamite	Ns	Adamite
Adamites	Np	Adamite
Adamitic	Apos	Adamitic
Adamitical	Apos	Adamitical
Adamiticaler	Acomp	Adamitical
Adamiticalest	Asup	Adamitical
Adamiticer	Acomp	Adamitic
Adamiticest	Asup	Adamitic
Adamitism	Ns	Adamitism
Adamitisms	Np	Adamitism
Adams	Np	Adam
Adams	Ns	Adams
Adamss	Np	Adams
Adapa	Ns	Adapa
Adapas	Np	Adapa
Adar	Ns	Adar
Adars	Np	Adar
Adas	Np	Ada
Addison	Ns	Addison
Addison's_disease	Ns	Addison's_disease
Addison's_diseases	Np	Addison's_disease
Addisonism	Ns	Addisonism
Addisonisms	Np	Addisonism
Addisons	Np	Addison
Addressograph	Ns	Addressograph
Addressographs	Np	Addressograph
Adelaide	Ns	Adelaide
Adelaides	Np	Adelaide
Adelidae	Ns	Adelidae
Adelidaes	Np	Adelidae
Adelie	Ns	Adelie
Adelies	Np	Adelie
Adelphian	Apos	Adelphian
Adelphian	Ns	Adelphian
Adelphianer	Acomp	Adelphian
Adelphianest	Asup	Adelphian
Adelphians	Np	Adelphian
Aden	Ns	Aden
Adens	Np	Aden
Adephaga	Ns	Adephaga
Adephagas	Np	Adephaga
Adige	Ns	Adige
Adiges	Np	Adige
Aditya	Ns	Aditya
Adityas	Np	Aditya
Adlerian	Apos	Adlerian
Adlerianer	Acomp	Adlerian
Adlerianest	Asup	Adlerian
Admiralties	Np	Admiralty
Admiralty	Ns	Admiralty
Adonic	Apos	Adonic
Adonic	Ns	Adonic
Adonicer	Acomp	Adonic
Adonicest	Asup	Adonic
Adonics	Np	Adonic
Adonis	Ns	Adonis
Adonises	Np	Adonis
Adrenalin	Ns	Adrenalin
Adrenalins	Np	Adrenalin
Adrianople	Ns	Adrianople
Adrianoples	Np	Adrianople
Adrianopolis	Ns	Adrianopolis
Adrianopolises	Np	Adrianopolis
Adriatic	Apos	Adriatic
Adriatic	Ns	Adriatic
Adriaticer	Acomp	Adriatic
Adriaticest	Asup	Adriatic
Adriatics	Np	Adriatic
Adullamite	Ns	Adullamite
Adullamites	Np	Adullamite
Advent	Ns	Advent
Adventism	Ns	Adventism
Adventisms	Np	Adventism
Adventist	Apos	Adventist
Adventist	Ns	Adventist
Adventister	Acomp	Adventist
Adventistest	Asup	Adventist
Adventists	Np	Adventist
Advents	Np	Advent
Aegean	Apos	Aegean
Aegean	Ns	Aegean
Aegeanner	Acomp	Aegean
Aegeannest	Asup	Aegean
Aegeans	Np	Aegean
Aegeria	Ns	Aegeria
Aegerias	Np	Aegeria
Aegeriidae	Ns	Aegeriidae
Aegeriidaes	Np	Aegeriidae
Aegina	Ns	Aegina
Aeginas	Np	Aegina
Aeginetan	Apos	Aeginetan
Aeginetan	Ns	Aeginetan
Aeginetaner	Acomp	Aeginetan
Aeginetanest	Asup	Aeginetan
Aeginetans	Np	Aeginetan
Aeginetic	Apos	Aeginetic
Aegineticer	Acomp	Aeginetic
Aegineticest	Asup	Aeginetic
Aegospotami	Ns	Aegospotami
Aegospotamis	Np	Aegospotami
Aeneas	Ns	Aeneas
Aeneases	Np	Aeneas
Aeneid	Ns	Aeneid
Aeneids	Np	Aeneid
Aeolia	Ns	Aeolia
Aeolian	Apos	Aeolian
Aeolian	Ns	Aeolian
Aeolianner	Acomp	Aeolian
Aeoliannest	Asup	Aeolian
Aeolians	Np	Aeolian
Aeolias	Np	Aeolia
Aeolic	Apos	Aeolic
Aeolic	Ns	Aeolic
Aeolicer	Acomp	Aeolic
Aeolicest	Asup	Aeolic
Aeolics	Np	Aeolic
Aeolis	Ns	Aeolis
Aeolises	Np	Aeolis
Aeolus	Ns	Aeolus
Aeoluses	Np	Aeolus
Aeschylean	Apos	Aeschylean
Aeschyleanner	Acomp	Aeschylean
Aeschyleannest	Asup	Aeschylean
Aeschylus	Ns	Aeschylus
Aeschyluses	Np	Aeschylus
Aesculapian	Apos	Aesculapian
Aesculapianer	Acomp	Aesculapian
Aesculapianest	Asup	Aesculapian
Aesculapius	Ns	Aesculapius
Aesculapiuses	Np	Aesculapius
Aesir	Ns	Aesir
Aesirs	Np	Aesir
Aesop	Ns	Aesop
Aesopian	Apos	Aesopian
Aesopianer	Acomp	Aesopian
Aesopianest	Asup	Aesopian
Aesopic	Apos	Aesopic
Aesopicer	Acomp	Aesopic
Aesopicest	Asup	Aesopic
Aesops	Np	Aesop
Aetolia	Ns	Aetolia
Aetolian	Apos	Aetolian
Aetolian	Ns	Aetolian
Aetolianer	Acomp	Aetolian
Aetolianest	Asup	Aetolian
Aetolians	Np	Aetolian
Aetolias	Np	Aetolia
Afghan	Apos	Afghan
Afghan	Ns	Afghan
Afghan_government	Ns	Afghan_government
Afghan_governments	Np	Afghan_government
Afghanistan	Ns	Afghanistan
Afghanistani	Apos	Afghanistani
Afghanistanier	Acomp	Afghanistani
Afghanistaniest	Asup	Afghanistani
Afghanistans	Np	Afghanistan
Afghanner	Acomp	Afghan
Afghannest	Asup	Afghan
Afghans	Np	Afghan
Aframerican	Apos	Aframerican
Aframerican	Ns	Aframerican
Aframericaner	Acomp	Aframerican
Aframericanest	Asup	Aframerican
Aframericans	Np	Aframerican
Afrasian	Apos	Afrasian
Afrasian	Ns	Afrasian
Afrasianer	Acomp	Afrasian
Afrasianest	Asup	Afrasian
Afrasians	Np	Afrasian
Africa	Ns	Africa
African	Apos	African
African	Ns	African
African_American	Ns	African_American
African_Americans	Np	African_American
African_National_Congress	Ns	African_National_Congress
African_National_Congresss	Np	African_National_Congress
Africander	Apos	Africander
Africander	Ns	Africander
Africanderer	Acomp	Africander
Africanderest	Asup	Africander
Africanders	Np	Africander
Africaner	Acomp	African
Africanest	Asup	African
Africanisation	Ns	Africanisation
Africanisations	Np	Africanisation
Africanism	Ns	Africanism
Africanisms	Np	Africanism
Africanist	Apos	Africanist
Africanist	Ns	Africanist
Africanister	Acomp	Africanist
Africanistest	Asup	Africanist
Africanists	Np	Africanist
Africanization	Ns	Africanization
Africanizations	Np	Africanization
Africanize	Vinf|presnot3s	Africanize
Africanized	Vpast	Africanize
Africanized	Vppart	Africanize
Africanizes	Vpres3s	Africanize
Africanizing	Vprespart	Africanize
Africans	Np	African
Africas	Np	Africa
Afrikaans	Ns	Afrikaans
Afrikaanses	Np	Afrikaans
Afrikander	Apos	Afrikander
Afrikander	Ns	Afrikander
Afrikanderer	Acomp	Afrikander
Afrikanderest	Asup	Afrikander
Afrikanders	Np	Afrikander
Afrikaner	Apos	Afrikaner
Afrikaner	Ns	Afrikaner
Afrikanerdom	Ns	Afrikanerdom
Afrikanerdoms	Np	Afrikanerdom
Afrikanerer	Acomp	Afrikaner
Afrikanerest	Asup	Afrikaner
Afrikanerize	Vinf|presnot3s	Afrikanerize
Afrikanerized	Vpast	Afrikanerize
Afrikanerized	Vppart	Afrikanerize
Afrikanerizes	Vpres3s	Afrikanerize
Afrikanerizing	Vprespart	Afrikanerize
Afrikaners	Np	Afrikaner
Afro	Apos	Afro
Afro	Ns	Afro
Afro-American	Ns	Afro-American
Afro-Americans	Np	Afro-American
Afro-Asian	Apos	Afro-Asian
Afro-Asianer	Acomp	Afro-Asian
Afro-Asianest	Asup	Afro-Asian
Afroer	Acomp	Afro
Afroest	Asup	Afro
Afros	Np	Afro
Ag	Ns	Ag
Aga_Khan	Ns	Aga_Khan
Aga_Khans	Np	Aga_Khan
Agamemnon	Ns	Agamemnon
Agamemnons	Np	Agamemnon
Agamidae	Ns	Agamidae
Agamidaes	Np	Agamidae
Agaricaceae	Ns	Agaricaceae
Agaricaceaes	Np	Agaricaceae
Agaricales	Ns	Agaricales
Agaricaless	Np	Agaricales
Agaristidae	Ns	Agaristidae
Agaristidaes	Np	Agaristidae
Agency_for_International_Development	Ns	Agency_for_International_Development
Agency_for_International_Developments	Np	Agency_for_International_Development
Aggadah	Ns	Aggadah
Aggadahs	Np	Aggadah
Aggie	Ns	Aggie
Aggies	Np	Aggie
Agincourt	Ns	Agincourt
Agincourts	Np	Agincourt
Aglossa	Ns	Aglossa
Aglossas	Np	Aglossa
Aglypha	Ns	Aglypha
Aglyphas	Np	Aglypha
Agnatha	Ns	Agnatha
Agnathas	Np	Agnatha
Agni	Ns	Agni
Agnis	Np	Agni
Agrionidae	Ns	Agrionidae
Agrionidaes	Np	Agrionidae
Agrippa	Ns	Agrippa
Agrippas	Np	Agrippa
Ags	Np	Ag
Ahab	Ns	Ahab
Ahabs	Np	Ahab
Ahriman	Ns	Ahriman
Ahrimans	Np	Ahriman
Aidoneus	Ns	Aidoneus
Aidoneuses	Np	Aidoneus
Ainu	Apos	Ainu
Ainu	Ns	Ainu
Ainuer	Acomp	Ainu
Ainuest	Asup	Ainu
Ainus	Np	Ainu
Air_Force_Base	Ns	Air_Force_Base
Air_Force_Bases	Np	Air_Force_Base
Aire	Ns	Aire
Airedale	Ns	Airedale
Airedales	Np	Airedale
Aires	Np	Aire
Airstrip	N	Airstrip
Airstrip	Ns	Airstrip
Airstrips	Np	Airstrip
Aizoaceae	Ns	Aizoaceae
Aizoaceaes	Np	Aizoaceae
Ajax	Ns	Ajax
Ajaxes	Np	Ajax
Ajuga	Ns	Ajuga
Ajugas	Np	Ajuga
Akaba	Ns	Akaba
Akabas	Np	Akaba
Akan	Apos	Akan
Akan	Ns	Akan
Akaner	Acomp	Akan
Akanest	Asup	Akan
Akans	Np	Akan
Akela	Ns	Akela
Akelas	Np	Akela
Akira_Kurosawa	Ns	Akira_Kurosawa
Akira_Kurosawas	Np	Akira_Kurosawa
Akita	Ns	Akita
Akitas	Np	Akita
Akkadian	Apos	Akkadian
Akkadian	Ns	Akkadian
Akkadianer	Acomp	Akkadian
Akkadianest	Asup	Akkadian
Akkadians	Np	Akkadian
Akromyodi	Ns	Akromyodi
Akromyodis	Np	Akromyodi
Akron	Ns	Akron
Akrons	Np	Akron
Al	Ns	Al
Al_Capone	Ns	Al_Capone
Al_Capones	Np	Al_Capone
Al_Pacino	Ns	Al_Pacino
Al_Pacinos	Np	Al_Pacino
Alabama	Ns	Alabama
Alabaman	Ns	Alabaman
Alabamans	Np	Alabaman
Alabamas	Np	Alabama
Alabamian	Ns	Alabamian
Alabamians	Np	Alabamian
Aladdin	Ns	Aladdin
Aladdins	Np	Aladdin
Alamo	Ns	Alamo
Alamoes	Np	Alamo
Alaouite	Apos	Alaouite
Alaouite	Ns	Alaouite
Alaouiter	Acomp	Alaouite
Alaouites	Np	Alaouite
Alaouitest	Asup	Alaouite
Alaska	Ns	Alaska
Alaskan	Ns	Alaskan
Alaskans	Np	Alaskan
Alaskas	Np	Alaska
Alaudidae	Ns	Alaudidae
Alaudidaes	Np	Alaudidae
Alawite	Apos	Alawite
Alawite	Ns	Alawite
Alawiter	Acomp	Alawite
Alawites	Np	Alawite
Alawitest	Asup	Alawite
Albania	Ns	Albania
Albanian	Apos	Albanian
Albanian	Ns	Albanian
Albanianer	Acomp	Albanian
Albanianest	Asup	Albanian
Albanians	Np	Albanian
Albanias	Np	Albania
Albanies	Np	Albany
Albany	Ns	Albany
Albers	Ns	Albers
Alberss	Np	Albers
Albert_Einstein	Ns	Albert_Einstein
Albert_Einsteins	Np	Albert_Einstein
Albert_Finney	Ns	Albert_Finney
Albert_Finneys	Np	Albert_Finney
Alberta	Ns	Alberta
Albertas	Np	Alberta
Albian	Apos	Albian
Albian	Ns	Albian
Albianer	Acomp	Albian
Albianes	Np	Albian
Albianest	Asup	Albian
Albigenses	Ns	Albigenses
Albigensess	Np	Albigenses
Albigensian	Apos	Albigensian
Albigensian	Ns	Albigensian
Albigensianer	Acomp	Albigensian
Albigensianest	Asup	Albigensian
Albigensianism	Ns	Albigensianism
Albigensianisms	Np	Albigensianism
Albigensians	Np	Albigensian
Albion	Ns	Albion
Albions	Np	Albion
Albuginaceae	Ns	Albuginaceae
Albuginaceaes	Np	Albuginaceae
Albuquerque	Ns	Albuquerque
Albuquerques	Np	Albuquerque
Alcaeus	Ns	Alcaeus
Alcaeuses	Np	Alcaeus
Alcaic	Ns	Alcaic
Alcaics	Np	Alcaic
Alcedinidae	Ns	Alcedinidae
Alcedinidaes	Np	Alcedinidae
Alcelaphinae	Ns	Alcelaphinae
Alcelaphinaes	Np	Alcelaphinae
Alcidae	Ns	Alcidae
Alcidaes	Np	Alcidae
Alcides	Ns	Alcides
Alcideses	Np	Alcides
Alcoran	Ns	Alcoran
Alcoranic	Apos	Alcoranic
Alcoranicer	Acomp	Alcoranic
Alcoranicest	Asup	Alcoranic
Alcorans	Np	Alcoran
Alcyonacea	Ns	Alcyonacea
Alcyonaceas	Np	Alcyonacea
Alcyonaria	Ns	Alcyonaria
Alcyonarias	Np	Alcyonaria
Aldebaran	Ns	Aldebaran
Aldebarans	Np	Aldebaran
Alderney	Ns	Alderney
Alderneys	Np	Alderney
Aldine	Apos	Aldine
Aldine	Ns	Aldine
Aldiner	Acomp	Aldine
Aldines	Np	Aldine
Aldinest	Asup	Aldine
Aldous_Huxley	Ns	Aldous_Huxley
Aldous_Huxleys	Np	Aldous_Huxley
Alec_Baldwin	Ns	Alec_Baldwin
Alec_Baldwins	Np	Alec_Baldwin
Alemanni	Ns	Alemanni
Alemannia	Ns	Alemannia
Alemannian	Apos	Alemannian
Alemannianer	Acomp	Alemannian
Alemannianest	Asup	Alemannian
Alemannias	Np	Alemannia
Alemannic	Apos	Alemannic
Alemannic	Ns	Alemannic
Alemannicer	Acomp	Alemannic
Alemannices	Np	Alemannic
Alemannicest	Asup	Alemannic
Alemannis	Np	Alemanni
Alencon	Ns	Alencon
Alencons	Np	Alencon
Aleppo	Ns	Aleppo
Aleppoes	Np	Aleppo
Aleurites	Ns	Aleurites
Aleuritess	Np	Aleurites
Aleut	Apos	Aleut
Aleut	Ns	Aleut
Aleuter	Acomp	Aleut
Aleutest	Asup	Aleut
Aleutian	Apos	Aleutian
Aleutian	Ns	Aleutian
Aleutianer	Acomp	Aleutian
Aleutianest	Asup	Aleutian
Aleutians	Np	Aleutian
Aleuts	Np	Aleut
Alexander	Ns	Alexander
Alexander_Graham_Bell	Ns	Alexander_Graham_Bell
Alexander_Graham_Bells	Np	Alexander_Graham_Bell
Alexander_Hamilton	Ns	Alexander_Hamilton
Alexander_Hamiltons	Np	Alexander_Hamilton
Alexanders	Np	Alexander
Alexandria	Ns	Alexandria
Alexandrian	Apos	Alexandrian
Alexandrian	Ns	Alexandrian
Alexandrianer	Acomp	Alexandrian
Alexandrianest	Asup	Alexandrian
Alexandrians	Np	Alexandrian
Alexandrias	Np	Alexandria
Alexandrine	Apos	Alexandrine
Alexandrine	Ns	Alexandrine
Alexandriner	Acomp	Alexandrine
Alexandrines	Np	Alexandrine
Alexandrinest	Asup	Alexandrine
Alexandrinism	Ns	Alexandrinism
Alexandrinismes	Np	Alexandrinism
Alf	Ns	Alf
Alfred_Hitchcock	Ns	Alfred_Hitchcock
Alfred_Hitchcocks	Np	Alfred_Hitchcock
Alfs	Np	Alf
Algeria	Ns	Algeria
Algerian	Apos	Algerian
Algerian	Ns	Algerian
Algerianer	Acomp	Algerian
Algerianest	Asup	Algerian
Algerians	Np	Algerian
Algerias	Np	Algeria
Algerine	Ns	Algerine
Algerines	Np	Algerine
Algiers	Ns	Algiers
Algierses	Np	Algiers
Algol	Ns	Algol
Algols	Np	Algol
Algonkian	Apos	Algonkian
Algonkian	Ns	Algonkian
Algonkianer	Acomp	Algonkian
Algonkianest	Asup	Algonkian
Algonkians	Np	Algonkian
Algonkin	Apos	Algonkin
Algonkin	Ns	Algonkin
Algonkiner	Acomp	Algonkin
Algonkinest	Asup	Algonkin
Algonkins	Np	Algonkin
Algonquian	Apos	Algonquian
Algonquian	Ns	Algonquian
Algonquianer	Acomp	Algonquian
Algonquianest	Asup	Algonquian
Algonquians	Np	Algonquian
Algonquin	Apos	Algonquin
Algonquin	Ns	Algonquin
Algonquiner	Acomp	Algonquin
Algonquinest	Asup	Algonquin
Algonquins	Np	Algonquin
Alice	Ns	Alice
Alice-in-Wonderland	Apos	Alice-in-Wonderland
Alice-in-Wonderlander	Acomp	Alice-in-Wonderland
Alice-in-Wonderlandest	Asup	Alice-in-Wonderland
Alices	Np	Alice
Alismaceae	Ns	Alismaceae
Alismaceaes	Np	Alismaceae
Alkoran	Ns	Alkoran
Alkoranic	Apos	Alkoranic
Alkoranicer	Acomp	Alkoranic
Alkoranicest	Asup	Alkoranic
Alkorans	Np	Alkoran
Allah	Ns	Allah
Allahs	Np	Allah
Allantoidea	Ns	Allantoidea
Allantoideas	Np	Allantoidea
Alleghenies	Ns	Alleghenies
Allegheniess	Np	Alleghenies
Allegheny	Apos	Allegheny
Alleghenyer	Acomp	Allegheny
Alleghenyest	Asup	Allegheny
Alleynian	Ns	Alleynian
Alleynians	Np	Alleynian
Allhallowmas	Ns	Allhallowmas
Allhallowmases	Np	Allhallowmas
Allhallows	Ns	Allhallows
Allhallowses	Np	Allhallows
Allhallowtide	Ns	Allhallowtide
Allhallowtides	Np	Allhallowtide
Allies	Ns	Allies
Alliess	Np	Allies
Almagest	Ns	Almagest
Almagests	Np	Almagest
Almighties	Np	Almighty
Almighty	Ns	Almighty
Alpha	Ns	Alpha
Alphas	Np	Alpha
Alpine	Apos	Alpine
Alpiner	Acomp	Alpine
Alpinest	Asup	Alpine
Alpinist	Ns	Alpinist
Alpinists	Np	Alpinist
Alps	Ns	Alps
Alpses	Np	Alps
Als	Np	Al
Alsace	Ns	Alsace
Alsaces	Np	Alsace
Alsatia	Ns	Alsatia
Alsatian	Apos	Alsatian
Alsatian	Ns	Alsatian
Alsatianer	Acomp	Alsatian
Alsatianest	Asup	Alsatian
Alsatians	Np	Alsatian
Alsatias	Np	Alsatia
Altaian	Apos	Altaian
Altaian	Ns	Altaian
Altaianer	Acomp	Altaian
Altaianest	Asup	Altaian
Altaians	Np	Altaian
Altaic	Apos	Altaic
Altaic	Ns	Altaic
Altaicer	Acomp	Altaic
Altaicest	Asup	Altaic
Altaics	Np	Altaic
Alundum	Ns	Alundum
Alundums	Np	Alundum
Alzheimer's_disease	Ns	Alzheimer's_disease
Alzheimer's_diseases	Np	Alzheimer's_disease
Am	Ns	Am
Amalekite	Ns	Amalekite
Amalekites	Np	Amalekite
Amaterasu	Ns	Amaterasu
Amaterasus	Np	Amaterasu
Amati	Ns	Amati
Amatis	Np	Amati
Amazon	Ns	Amazon
Amazon_basin	Ns	Amazon_basin
Amazon_basins	Np	Amazon_basin
Amazonia	N	Amazonia
Amazonia	Ns	Amazonia
Amazonian	Apos	Amazonian
Amazonianer	Acomp	Amazonian
Amazonianest	Asup	Amazonian
Amazonias	Np	Amazonia
Amazons	Np	Amazon
Amen	Ns	Amen
Amens	Np	Amen
America	Ns	America
American	Apos	American
American	Ns	American
American_Civil_War	Ns	American_Civil_War
American_Civil_Wars	Np	American_Civil_War
American_Dream	Ns	American_Dream
American_Dreams	Np	American_Dream
American_Indian	Apos	American_Indian
American_Revolution	Ns	American_Revolution
American_Revolutions	Np	American_Revolution
American_beauty	Ns	American_beauty
American_beautys	Np	American_beauty
American_crocodile	Ns	American_crocodile
American_crocodiles	Np	American_crocodile
American_dream	Ns	American_dream
American_dreams	Np	American_dream
American_eagle	Ns	American_eagle
American_eagles	Np	American_eagle
American_flag	Ns	American_flag
American_flags	Np	American_flag
American_football	Ns	American_football
American_footballs	Np	American_football
American_people	Ns	American_people
American_peoples	Np	American_people
American_revolution	Ns	American_revolution
American_revolutions	Np	American_revolution
American_school	Ns	American_school
American_schools	Np	American_school
American_way_of_life	Ns	American_way_of_life
American_way_of_lifes	Np	American_way_of_life
Americana	Ns	Americana
Americanas	Np	Americana
Americaner	Acomp	American
Americanest	Asup	American
Americanisation	Ns	Americanisation
Americanisations	Np	Americanisation
Americanise	Vinf|presnot3s	Americanise
Americanised	Vpast	Americanise
Americanised	Vppart	Americanise
Americaniser	Ns	Americaniser
Americanisers	Np	Americaniser
Americanises	Vpres3s	Americanise
Americanising	Vprespart	Americanise
Americanism	Ns	Americanism
Americanisms	Np	Americanism
Americanist	Apos	Americanist
Americanist	Ns	Americanist
Americanister	Acomp	Americanist
Americanistest	Asup	Americanist
Americanists	Np	Americanist
Americanization	Ns	Americanization
Americanizations	Np	Americanization
Americanize	Vinf|presnot3s	Americanize
Americanized	Vpast	Americanize
Americanized	Vppart	Americanize
Americanizer	Ns	Americanizer
Americanizers	Np	Americanizer
Americanizes	Vpres3s	Americanize
Americanizing	Vprespart	Americanize
Americanlier	Rcomp	Americanly
Americanliest	Rsup	Americanly
Americanly	Rpos	Americanly
Americans	Np	American
Americas	Np	America
Americas	Ns	Americas
Americass	Np	Americas
Amerind	Apos	Amerind
Amerind	Ns	Amerind
Amerinder	Acomp	Amerind
Amerindest	Asup	Amerind
Amerindian	Apos	Amerindian
Amerindian	Ns	Amerindian
Amerindianer	Acomp	Amerindian
Amerindianest	Asup	Amerindian
Amerindians	Np	Amerindian
Amerindic	Apos	Amerindic
Amerindicer	Acomp	Amerindic
Amerindicest	Asup	Amerindic
Amerinds	Np	Amerind
Amhara	Ns	Amhara
Amharas	Np	Amhara
Amharic	Apos	Amharic
Amharic	Ns	Amharic
Amharicer	Acomp	Amharic
Amharicest	Asup	Amharic
Amharics	Np	Amharic
Amish	Apos	Amish
Amish	Ns	Amish
Amisher	Acomp	Amish
Amishes	Np	Amish
Amishest	Asup	Amish
Amishman	Ns	Amishman
Amishmen	Np	Amishman
Amman	Ns	Amman
Ammans	Np	Amman
Ammonite	Apos	Ammonite
Ammonite	Ns	Ammonite
Ammoniter	Acomp	Ammonite
Ammonites	Np	Ammonite
Ammonitest	Asup	Ammonite
Amnesty_International	Ns	Amnesty_International
Amnesty_Internationals	Np	Amnesty_International
Amon	Ns	Amon
Amons	Np	Amon
Amor	Ns	Amor
Amors	Np	Amor
Amoy	Ns	Amoy
Amoys	Np	Amoy
Amphibia	Ns	Amphibia
Amphibias	Np	Amphibia
Ams	Np	Am
Amsterdam	Ns	Amsterdam
Amsterdams	Np	Amsterdam
Amur	Ns	Amur
Amurs	Np	Amur
Amytal	Ns	Amytal
Amytals	Np	Amytal
Ana	Ns	Ana
Anabaptism	Ns	Anabaptism
Anabaptisms	Np	Anabaptism
Anabaptist	Apos	Anabaptist
Anabaptist	Ns	Anabaptist
Anabaptister	Acomp	Anabaptist
Anabaptistest	Asup	Anabaptist
Anabaptisticallier	Rcomp	Anabaptistically
Anabaptisticalliest	Rsup	Anabaptistically
Anabaptistically	Rpos	Anabaptistically
Anabaptists	Np	Anabaptist
Anacreontic	Apos	Anacreontic
Anacreontic	Ns	Anacreontic
Anacreonticallier	Rcomp	Anacreontically
Anacreonticalliest	Rsup	Anacreontically
Anacreontically	Rpos	Anacreontically
Anacreonticer	Acomp	Anacreontic
Anacreonticest	Asup	Anacreontic
Anacreontics	Np	Anacreontic
Ananias	Ns	Ananias
Ananiases	Np	Ananias
Anapurna	Ns	Anapurna
Anapurnas	Np	Anapurna
Anas	Np	Ana
Anatolia	Ns	Anatolia
Anatolian	Apos	Anatolian
Anatolian	Ns	Anatolian
Anatolianer	Acomp	Anatolian
Anatolianest	Asup	Anatolian
Anatolians	Np	Anatolian
Anatolias	Np	Anatolia
Anchorage	Ns	Anchorage
Anchorages	Np	Anchorage
Ancohuma	Ns	Ancohuma
Ancohumas	Np	Ancohuma
Andalusia	Ns	Andalusia
Andalusian	Ns	Andalusian
Andalusians	Np	Andalusian
Andalusias	Np	Andalusia
Andean	Apos	Andean
Andeanner	Acomp	Andean
Andeannest	Asup	Andean
Andersen	Ns	Andersen
Andersens	Np	Andersen
Andes	Ns	Andes
Andeses	Np	Andes
Andorra	Ns	Andorra
Andorran	Apos	Andorran
Andorran	Ns	Andorran
Andorraner	Acomp	Andorran
Andorranest	Asup	Andorran
Andorrans	Np	Andorran
Andorras	Np	Andorra
Andrew	Ns	Andrew
Andrews	Np	Andrew
Andromeda	Ns	Andromeda
Andromedas	Np	Andromeda
Angel	Ns	Angel
Angeleno	Ns	Angeleno
Angelenos	Np	Angeleno
Angelica	Ns	Angelica
Angelicas	Np	Angelica
Angels	Np	Angel
Angelus	Ns	Angelus
Angeluses	Np	Angelus
Angevin	Apos	Angevin
Angevin	Ns	Angevin
Angeviner	Acomp	Angevin
Angevinest	Asup	Angevin
Angevins	Np	Angevin
Angle	Ns	Angle
Angles	Np	Angle
Anglian	Apos	Anglian
Anglian	Ns	Anglian
Anglianer	Acomp	Anglian
Anglianest	Asup	Anglian
Anglians	Np	Anglian
Anglican	Apos	Anglican
Anglican	Ns	Anglican
Anglicaner	Acomp	Anglican
Anglicanest	Asup	Anglican
Anglicanism	Ns	Anglicanism
Anglicanisms	Np	Anglicanism
Anglicanlier	Rcomp	Anglicanly
Anglicanliest	Rsup	Anglicanly
Anglicanly	Rpos	Anglicanly
Anglicans	Np	Anglican
Anglice	Rpos	Anglice
Anglicer	Rcomp	Anglice
Anglicest	Rsup	Anglice
Anglicise	Vinf|presnot3s	Anglicise
Anglicised	Vpast	Anglicise
Anglicised	Vppart	Anglicise
Anglicises	Vpres3s	Anglicise
Anglicising	Vprespart	Anglicise
Anglicism	Ns	Anglicism
Anglicisms	Np	Anglicism
Anglicist	Apos	Anglicist
Anglicist	Ns	Anglicist
Anglicister	Acomp	Anglicist
Anglicistest	Asup	Anglicist
Anglicists	Np	Anglicist
Anglicization	Ns	Anglicization
Anglicizations	Np	Anglicization
Anglicize	Vinf|presnot3s	Anglicize
Anglicized	Vpast	Anglicize
Anglicized	Vppart	Anglicize
Anglicizes	Vpres3s	Anglicize
Anglicizing	Vprespart	Anglicize
Anglified	Vpast	Anglify
Anglified	Vppart	Anglify
Anglifies	Vpres3s	Anglify
Anglify	Vinf|presnot3s	Anglify
Anglifying	Vprespart	Anglify
Anglist	Ns	Anglist
Anglists	Np	Anglist
Anglo	Ns	Anglo
Anglo-American	Ns	Anglo-American
Anglo-Americans	Np	Anglo-American
Anglo-Catholic	Apos	Anglo-Catholic
Anglo-Catholicer	Acomp	Anglo-Catholic
Anglo-Catholicest	Asup	Anglo-Catholic
Anglo-Indian	Apos	Anglo-Indian
Anglo-Indian	Ns	Anglo-Indian
Anglo-Indianer	Acomp	Anglo-Indian
Anglo-Indianest	Asup	Anglo-Indian
Anglo-Indians	Np	Anglo-Indian
Anglo-Irish	Ns	Anglo-Irish
Anglo-Irishs	Np	Anglo-Irish
Anglo-Saxon	Apos	Anglo-Saxon
Anglo-Saxon	Ns	Anglo-Saxon
Anglo-Saxoner	Acomp	Anglo-Saxon
Anglo-Saxonest	Asup	Anglo-Saxon
Anglo-Saxons	Np	Anglo-Saxon
Anglomania	Ns	Anglomania
Anglomanias	Np	Anglomania
Anglophil	Ns	Anglophil
Anglophile	Ns	Anglophile
Anglophiles	Np	Anglophile
Anglophilia	Ns	Anglophilia
Anglophiliac	Apos	Anglophiliac
Anglophiliacer	Acomp	Anglophiliac
Anglophiliacest	Asup	Anglophiliac
Anglophilias	Np	Anglophilia
Anglophilic	Apos	Anglophilic
Anglophilicer	Acomp	Anglophilic
Anglophilicest	Asup	Anglophilic
Anglophils	Np	Anglophil
Anglophobe	Ns	Anglophobe
Anglophobes	Np	Anglophobe
Anglophobia	Ns	Anglophobia
Anglophobias	Np	Anglophobia
Anglophobic	Apos	Anglophobic
Anglophobicer	Acomp	Anglophobic
Anglophobicest	Asup	Anglophobic
Anglophone	Apos	Anglophone
Anglophone	Ns	Anglophone
Anglophoner	Acomp	Anglophone
Anglophones	Np	Anglophone
Anglophonest	Asup	Anglophone
Anglos	Np	Anglo
Angola	Ns	Angola
Angolan	Apos	Angolan
Angolan	Ns	Angolan
Angolaner	Acomp	Angolan
Angolanest	Asup	Angolan
Angolans	Np	Angolan
Angolas	Np	Angola
Angolese	Ns	Angolese
Angoleses	Np	Angolese
Angora	Ns	Angora
Angoras	Np	Angora
Anguilla	Ns	Anguilla
Anguillan	Apos	Anguillan
Anguillaner	Acomp	Anguillan
Anguillanest	Asup	Anguillan
Anguillas	Np	Anguilla
Anguis	Ns	Anguis
Anguises	Np	Anguis
Angus	Ns	Angus
Anguses	Np	Angus
Anjelica_Huston	Ns	Anjelica_Huston
Anjelica_Hustons	Np	Anjelica_Huston
Anjou	Ns	Anjou
Anjous	Np	Anjou
Ankara	Ns	Ankara
Ankaras	Np	Ankara
Annam	Ns	Annam
Annamese	Apos	Annamese
Annamese	Ns	Annamese
Annameser	Acomp	Annamese
Annameses	Np	Annamese
Annamesest	Asup	Annamese
Annams	Np	Annam
Annapolis	Ns	Annapolis
Annapolises	Np	Annapolis
Annapurna	Ns	Annapurna
Annapurnas	Np	Annapurna
Annelida	Ns	Annelida
Annelidas	Np	Annelida
Annette_Bening	Ns	Annette_Bening
Annette_Benings	Np	Annette_Bening
Annwn	Ns	Annwn
Annwns	Np	Annwn
Antabuse	Ns	Antabuse
Antabuses	Np	Antabuse
Antananarivo	Ns	Antananarivo
Antananarivoes	Np	Antananarivo
Antarctic	Apos	Antarctic
Antarctic	Ns	Antarctic
Antarctica	Ns	Antarctica
Antarcticas	Np	Antarctica
Antarcticer	Acomp	Antarctic
Antarcticest	Asup	Antarctic
Antarctics	Np	Antarctic
Antares	Ns	Antares
Antareses	Np	Antares
Anthony_Hopkins	Ns	Anthony_Hopkins
Anthony_Hopkinss	Np	Anthony_Hopkins
Anthony_Perkins	Ns	Anthony_Perkins
Anthony_Perkinss	Np	Anthony_Perkins
Anthozoa	Ns	Anthozoa
Anthozoas	Np	Anthozoa
Anti-Sex	Apos	Anti-Sex
Anti-Sexer	Acomp	Anti-Sex
Anti-Sexest	Asup	Anti-Sex
Antichrist	Ns	Antichrist
Antichristian	Apos	Antichristian
Antichristianer	Acomp	Antichristian
Antichristianest	Asup	Antichristian
Antichrists	Np	Antichrist
Antigone	Ns	Antigone
Antigones	Np	Antigone
Antigua	Ns	Antigua
Antiguan	Apos	Antiguan
Antiguan	Ns	Antiguan
Antiguaner	Acomp	Antiguan
Antiguanest	Asup	Antiguan
Antiguans	Np	Antiguan
Antiguas	Np	Antigua
Antilles	Ns	Antilles
Antilleses	Np	Antilles
Antiochian	Ns	Antiochian
Antiochians	Np	Antiochian
Antofagasta	Ns	Antofagasta
Antofagastas	Np	Antofagasta
Antonies	Np	Antony
Antonio_Banderas	Ns	Antonio_Banderas
Antonio_Banderass	Np	Antonio_Banderas
Antony	Ns	Antony
Antrim	Ns	Antrim
Antrims	Np	Antrim
Antwerp	Ns	Antwerp
Antwerps	Np	Antwerp
Anu	Ns	Anu
Anubis	Ns	Anubis
Anubises	Np	Anubis
Anunnaki	Ns	Anunnaki
Anunnakis	Np	Anunnaki
Anus	Np	Anu
Anvers	Ns	Anvers
Anverses	Np	Anvers
Anzac	Ns	Anzac
Anzacs	Np	Anzac
Aosta	Ns	Aosta
Aostas	Np	Aosta
Apache	Apos	Apache
Apache	Ns	Apache
Apacher	Acomp	Apache
Apaches	Np	Apache
Apachest	Asup	Apache
Apalachicola	Ns	Apalachicola
Apalachicolas	Np	Apalachicola
Apennines	Ns	Apennines
Apenniness	Np	Apennines
Aphrodite	Ns	Aphrodite
Aphrodites	Np	Aphrodite
Apis	Ns	Apis
Apises	Np	Apis
Apocalypse	Ns	Apocalypse
Apocalypses	Np	Apocalypse
Apocrypha	Ns	Apocrypha
Apocryphas	Np	Apocrypha
Apollinian	Apos	Apollinian
Apollinianer	Acomp	Apollinian
Apollinianest	Asup	Apollinian
Apollo	Ns	Apollo
Apollonian	Apos	Apollonian
Apollonianer	Acomp	Apollonian
Apollonianest	Asup	Apollonian
Apollos	Np	Apollo
Appalachia	Ns	Appalachia
Appalachian	Apos	Appalachian
Appalachianer	Acomp	Appalachian
Appalachianest	Asup	Appalachian
Appalachias	Np	Appalachia
Appaloosa	Ns	Appaloosa
Appaloosas	Np	Appaloosa
Appenzell	Ns	Appenzell
Appenzells	Np	Appenzell
Apr	Ns	Apr
April	Ns	April
April_Fools'_day	Ns	April_Fools'_day
April_Fools'_days	Np	April_Fools'_day
April_fool	Ns	April_fool
April_fools	Np	April_fool
Aprils	Np	April
Aprs	Np	Apr
Apsu	Ns	Apsu
Apsus	Np	Apsu
Apulia	Ns	Apulia
Apulias	Np	Apulia
Apus	Ns	Apus
Apuses	Np	Apus
Aqaba	Ns	Aqaba
Aqabas	Np	Aqaba
Aquarius	Ns	Aquarius
Aquariuses	Np	Aquarius
Aquinas	Ns	Aquinas
Aquinases	Np	Aquinas
Aquitaine	Ns	Aquitaine
Aquitaines	Np	Aquitaine
Ar	Ns	Ar
Ara	Ns	Ara
Arab	Apos	Arab
Arab	Ns	Arab
Arab_world	Ns	Arab_world
Arab_worlds	Np	Arab_world
Araber	Acomp	Arab
Arabest	Asup	Arab
Arabia	Ns	Arabia
Arabian	Apos	Arabian
Arabian	Ns	Arabian
Arabian_Sea	Ns	Arabian_Sea
Arabian_Seas	Np	Arabian_Sea
Arabian_peninsula	Ns	Arabian_peninsula
Arabian_peninsulas	Np	Arabian_peninsula
Arabianer	Acomp	Arabian
Arabianest	Asup	Arabian
Arabians	Np	Arabian
Arabias	Np	Arabia
Arabic	Apos	Arabic
Arabic	Ns	Arabic
Arabicer	Acomp	Arabic
Arabicest	Asup	Arabic
Arabics	Np	Arabic
Arabist	Apos	Arabist
Arabist	Ns	Arabist
Arabister	Acomp	Arabist
Arabistest	Asup	Arabist
Arabists	Np	Arabist
Arabs	Np	Arab
Arachnida	Ns	Arachnida
Arachnidas	Np	Arachnida
Aragon	Ns	Aragon
Aragons	Np	Aragon
Aramaean	Apos	Aramaean
Aramaean	Ns	Aramaean
Aramaeaner	Acomp	Aramaean
Aramaeanest	Asup	Aramaean
Aramaeans	Np	Aramaean
Aramaic	Apos	Aramaic
Aramaic	Ns	Aramaic
Aramaicer	Acomp	Aramaic
Aramaicest	Asup	Aramaic
Aramaics	Np	Aramaic
Aramean	Apos	Aramean
Aramean	Ns	Aramean
Arameaner	Acomp	Aramean
Arameanest	Asup	Aramean
Arameans	Np	Aramean
Aran	Ns	Aran
Arans	Np	Aran
Arapaho	Apos	Arapaho
Arapaho	Ns	Arapaho
Arapahoe	Apos	Arapahoe
Arapahoe	Ns	Arapahoe
Arapahoer	Acomp	Arapaho
Arapahoer	Acomp	Arapahoe
Arapahoes	Np	Arapaho
Arapahoes	Np	Arapahoe
Arapahoest	Asup	Arapaho
Arapahoest	Asup	Arapahoe
Ararat	Ns	Ararat
Ararats	Np	Ararat
Aras	Np	Ara
Araucan	Apos	Araucan
Araucan	Ns	Araucan
Araucaner	Acomp	Araucan
Araucanest	Asup	Araucan
Araucanian	Apos	Araucanian
Araucanian	Ns	Araucanian
Araucanianer	Acomp	Araucanian
Araucanianest	Asup	Araucanian
Araucanians	Np	Araucanian
Araucans	Np	Araucan
Arawak	Apos	Arawak
Arawak	Ns	Arawak
Arawakan	Apos	Arawakan
Arawakan	Ns	Arawakan
Arawakaner	Acomp	Arawakan
Arawakanest	Asup	Arawakan
Arawakans	Np	Arawakan
Arawaker	Acomp	Arawak
Arawakest	Asup	Arawak
Arawaks	Np	Arawak
Arawn	Ns	Arawn
Arawns	Np	Arawn
Arcadia	Ns	Arcadia
Arcadian	Apos	Arcadian
Arcadian	Ns	Arcadian
Arcadianer	Acomp	Arcadian
Arcadianest	Asup	Arcadian
Arcadianism	Ns	Arcadianism
Arcadianisms	Np	Arcadianism
Arcadianlier	Rcomp	Arcadianly
Arcadianliest	Rsup	Arcadianly
Arcadianly	Rpos	Arcadianly
Arcadians	Np	Arcadian
Arcadias	Np	Arcadia
Arcadic	Apos	Arcadic
Arcadic	Ns	Arcadic
Arcadicer	Acomp	Arcadic
Arcadicest	Asup	Arcadic
Arcadics	Np	Arcadic
Arcady	Ns	Arcady
Arcadys	Np	Arcady
Archaean	Apos	Archaean
Archaean	Ns	Archaean
Archaeaner	Acomp	Archaean
Archaeanes	Np	Archaean
Archaeanest	Asup	Archaean
Archaeozoic	Ns	Archaeozoic
Archaeozoics	Np	Archaeozoic
Archean	Apos	Archean
Archean	Ns	Archean
Archeaner	Acomp	Archean
Archeanes	Np	Archean
Archeanest	Asup	Archean
Archilochus	Ns	Archilochus
Archilochuses	Np	Archilochus
Archimedean	Apos	Archimedean
Archimedeaner	Acomp	Archimedean
Archimedeanest	Asup	Archimedean
Archimedes	Ns	Archimedes
Archimedess	Np	Archimedes
Arctic	Apos	Arctic
Arctic	Ns	Arctic
Arcticallier	Rcomp	Arctically
Arcticalliest	Rsup	Arctically
Arctically	Rpos	Arctically
Arcticer	Acomp	Arctic
Arcticest	Asup	Arctic
Arctics	Np	Arctic
Arcturus	Ns	Arcturus
Arcturuses	Np	Arcturus
Ardennes	Ns	Ardennes
Ardenneses	Np	Ardennes
Areopagite	Apos	Areopagite
Areopagite	Ns	Areopagite
Areopagiter	Acomp	Areopagite
Areopagites	Np	Areopagite
Areopagitest	Asup	Areopagite
Areopagitic	Apos	Areopagitic
Areopagiticer	Acomp	Areopagitic
Areopagiticest	Asup	Areopagitic
Areopagus	Ns	Areopagus
Areopaguses	Np	Areopagus
Ares	Np	Ar
Aretha_Franklin	Ns	Aretha_Franklin
Aretha_Franklins	Np	Aretha_Franklin
Argentina	Ns	Argentina
Argentinas	Np	Argentina
Argentine	Apos	Argentine
Argentine	Ns	Argentine
Argentiner	Acomp	Argentine
Argentines	Np	Argentine
Argentinest	Asup	Argentine
Argentinian	Apos	Argentinian
Argentinian	Ns	Argentinian
Argentinianer	Acomp	Argentinian
Argentinianest	Asup	Argentinian
Argentinians	Np	Argentinian
Argiope	Ns	Argiope
Argiopes	Np	Argiope
Argive	Apos	Argive
Argive	Ns	Argive
Argiver	Acomp	Argive
Argives	Np	Argive
Argivest	Asup	Argive
Argo	Ns	Argo
Argonaut	Ns	Argonaut
Argonauts	Np	Argonaut
Argonne	Ns	Argonne
Argonnes	Np	Argonne
Argos	Np	Argo
Argos	Ns	Argos
Argoss	Np	Argos
Argus	Ns	Argus
Argus-eyed	Apos	Argus-eyed
Argus-eyeder	Acomp	Argus-eyed
Argus-eyedest	Asup	Argus-eyed
Arguses	Np	Argus
Argyle	Ns	Argyle
Argyles	Np	Argyle
Argyll	Ns	Argyll
Argylls	Np	Argyll
Argyrol	Ns	Argyrol
Argyrols	Np	Argyrol
Arhat	Ns	Arhat
Arhats	Np	Arhat
Ariadne	Ns	Ariadne
Ariadnes	Np	Ariadne
Arian	Apos	Arian
Arian	Ns	Arian
Arianer	Acomp	Arian
Arianest	Asup	Arian
Arianism	Ns	Arianism
Arianisms	Np	Arianism
Arianrhod	Ns	Arianrhod
Arianrhods	Np	Arianrhod
Arians	Np	Arian
Arica	Ns	Arica
Aricas	Np	Arica
Aries	Ns	Aries
Arieses	Np	Aries
Aristarchus	Ns	Aristarchus
Aristarchuses	Np	Aristarchus
Aristophanes	Ns	Aristophanes
Aristophaneses	Np	Aristophanes
Aristotelean	Apos	Aristotelean
Aristoteleaner	Acomp	Aristotelean
Aristoteleanest	Asup	Aristotelean
Aristotelian	Apos	Aristotelian
Aristotelian	Ns	Aristotelian
Aristotelianer	Acomp	Aristotelian
Aristotelianest	Asup	Aristotelian
Aristotelianism	Ns	Aristotelianism
Aristotelianisms	Np	Aristotelianism
Aristotelians	Np	Aristotelian
Aristotle	Ns	Aristotle
Aristotles	Np	Aristotle
Arius	Ns	Arius
Ariuses	Np	Arius
Arizona	Ns	Arizona
Arizonan	Ns	Arizonan
Arizonans	Np	Arizonan
Arizonas	Np	Arizona
Arizonian	Ns	Arizonian
Arizonians	Np	Arizonian
Arkansan	Apos	Arkansan
Arkansan	Ns	Arkansan
Arkansaner	Acomp	Arkansan
Arkansanest	Asup	Arkansan
Arkansans	Np	Arkansan
Arkansas	Ns	Arkansas
Arkansases	Np	Arkansas
Arkansawyer	Apos	Arkansawyer
Arkansawyer	Ns	Arkansawyer
Arkansawyerer	Acomp	Arkansawyer
Arkansawyerest	Asup	Arkansawyer
Arkansawyers	Np	Arkansawyer
Arlberg	Ns	Arlberg
Arlbergs	Np	Arlberg
Armageddon	Ns	Armageddon
Armageddons	Np	Armageddon
Armagh	Ns	Armagh
Armaghs	Np	Armagh
Armagnac	Ns	Armagnac
Armagnacs	Np	Armagnac
Armenia	Ns	Armenia
Armenian	Apos	Armenian
Armenian	Ns	Armenian
Armenianer	Acomp	Armenian
Armenianest	Asup	Armenian
Armenians	Np	Armenian
Armenias	Np	Armenia
Armin	Ns	Armin
Arminian	Apos	Arminian
Arminian	Ns	Arminian
Arminianer	Acomp	Arminian
Arminianest	Asup	Arminian
Arminianism	Ns	Arminianism
Arminianisms	Np	Arminianism
Arminians	Np	Arminian
Arminius	Ns	Arminius
Arminiuses	Np	Arminius
Armins	Np	Armin
Armorica	Ns	Armorica
Armorican	Apos	Armorican
Armorican	Ns	Armorican
Armoricaner	Acomp	Armorican
Armoricanest	Asup	Armorican
Armoricans	Np	Armorican
Armoricas	Np	Armorica
Armstrong	Ns	Armstrong
Armstrongs	Np	Armstrong
Army_officer	Ns	Army_officer
Army_officers	Np	Army_officer
Army_sergeant	Ns	Army_sergeant
Army_sergeants	Np	Army_sergeant
Arnhem	Ns	Arnhem
Arnhems	Np	Arnhem
Arno	Ns	Arno
Arnoes	Np	Arno
Arnold_Schwarzenegger	Ns	Arnold_Schwarzenegger
Arnold_Schwarzeneggers	Np	Arnold_Schwarzenegger
Arran	Ns	Arran
Arrans	Np	Arran
Arretine	Apos	Arretine
Arretiner	Acomp	Arretine
Arretinest	Asup	Arretine
Art_Blakey	Ns	Art_Blakey
Art_Blakeys	Np	Art_Blakey
Artemis	Ns	Artemis
Artemises	Np	Artemis
Arthropoda	Ns	Arthropoda
Arthropodas	Np	Arthropoda
Arthur	Ns	Arthur
Arthur_Koestler	Ns	Arthur_Koestler
Arthur_Koestlers	Np	Arthur_Koestler
Arthur_Miller	Ns	Arthur_Miller
Arthur_Millers	Np	Arthur_Miller
Arthur_Rubinstein	Ns	Arthur_Rubinstein
Arthur_Rubinsteins	Np	Arthur_Rubinstein
Arthurs	Np	Arthur
Artois	Ns	Artois
Artoises	Np	Artois
Aruba	Ns	Aruba
Arubas	Np	Aruba
Aruru	Ns	Aruru
Arurus	Np	Aruru
Aryan	Apos	Aryan
Aryan	Ns	Aryan
Aryanise	Vinf|presnot3s	Aryanise
Aryanised	Vpast	Aryanise
Aryanised	Vppart	Aryanise
Aryanises	Vpres3s	Aryanise
Aryanising	Vprespart	Aryanise
Aryanize	Vinf|presnot3s	Aryanize
Aryanized	Vpast	Aryanize
Aryanized	Vppart	Aryanize
Aryanizes	Vpres3s	Aryanize
Aryanizing	Vprespart	Aryanize
Aryanner	Acomp	Aryan
Aryannest	Asup	Aryan
Aryans	Np	Aryan
As	Np	A
Ascension	Ns	Ascension
Ascensions	Np	Ascension
Ascensiontide	Ns	Ascensiontide
Ascensiontides	Np	Ascensiontide
Asclepiad	Ns	Asclepiad
Asclepiadean	Apos	Asclepiadean
Asclepiadean	Ns	Asclepiadean
Asclepiadeaner	Acomp	Asclepiadean
Asclepiadeanest	Asup	Asclepiadean
Asclepiadeans	Np	Asclepiadean
Asclepiads	Np	Asclepiad
Asgard	Ns	Asgard
Asgardes	Np	Asgard
Ashanti	Apos	Ashanti
Ashanti	Ns	Ashanti
Ashantier	Acomp	Ashanti
Ashantiest	Asup	Ashanti
Ashantis	Np	Ashanti
Ashkenazi	Ns	Ashkenazi
Ashkenazic	Apos	Ashkenazic
Ashkenazicer	Acomp	Ashkenazic
Ashkenazicest	Asup	Ashkenazic
Ashkenazis	Np	Ashkenazi
Ashkhabad	Ns	Ashkhabad
Ashkhabads	Np	Ashkhabad
Ashtoreth	Ns	Ashtoreth
Ashtoreths	Np	Ashtoreth
Ashur	Ns	Ashur
Ashurs	Np	Ashur
Asia	Ns	Asia
Asia_Minor	Ns	Asia_Minor
Asia_Minors	Np	Asia_Minor
Asian	Apos	Asian
Asian	Ns	Asian
Asian-American	Ns	Asian-American
Asian-Americans	Np	Asian-American
Asian_flu	Ns	Asian_flu
Asian_flus	Np	Asian_flu
Asianner	Acomp	Asian
Asiannest	Asup	Asian
Asians	Np	Asian
Asias	Np	Asia
Asiatic	Apos	Asiatic
Asiatic	Ns	Asiatic
Asiaticallier	Rcomp	Asiatically
Asiaticalliest	Rsup	Asiatically
Asiatically	Rpos	Asiatically
Asiaticer	Acomp	Asiatic
Asiaticest	Asup	Asiatic
Asiatics	Np	Asiatic
Asperges	Ns	Asperges
Aspergeses	Np	Asperges
Assam	Ns	Assam
Assamese	Apos	Assamese
Assamese	Ns	Assamese
Assameser	Acomp	Assamese
Assameses	Np	Assamese
Assamesest	Asup	Assamese
Assams	Np	Assam
Assassin	Ns	Assassin
Assassins	Np	Assassin
Assemblies	Np	Assembly
Assembly	Ns	Assembly
Assiniboin	Ns	Assiniboin
Assiniboine	Ns	Assiniboine
Assiniboines	Np	Assiniboine
Assiniboins	Np	Assiniboin
Associated_Press	Ns	Associated_Press
Associated_Presss	Np	Associated_Press
Assuan	Ns	Assuan
Assuans	Np	Assuan
Assumption	Ns	Assumption
Assumptions	Np	Assumption
Assur	Ns	Assur
Assurs	Np	Assur
Assyria	Ns	Assyria
Assyrian	Apos	Assyrian
Assyrian	Ns	Assyrian
Assyrianer	Acomp	Assyrian
Assyrianest	Asup	Assyrian
Assyrians	Np	Assyrian
Assyrias	Np	Assyria
Assyriologies	Np	Assyriology
Assyriologist	Ns	Assyriologist
Assyriologists	Np	Assyriologist
Assyriology	Ns	Assyriology
Astarte	Ns	Astarte
Astartes	Np	Astarte
Asteroidea	Ns	Asteroidea
Asteroideas	Np	Asteroidea
Asterope	Ns	Asterope
Asteropes	Np	Asterope
Aston	N	Aston
Astrakhan	Ns	Astrakhan
Astrakhans	Np	Astrakhan
Asturian	Ns	Asturian
Asturians	Np	Asturian
Asturias	Ns	Asturias
Asturiass	Np	Asturias
Asuncion	Ns	Asuncion
Asuncions	Np	Asuncion
Asura	Ns	Asura
Asuras	Np	Asura
Aswan	Ns	Aswan
Aswans	Np	Aswan
At	Ns	At
Atabrine	Ns	Atabrine
Atabrines	Np	Atabrine
Atakapa	Ns	Atakapa
Atakapas	Np	Atakapa
Atarax	Ns	Atarax
Ataraxes	Np	Atarax
Ate	Ns	Ate
Ates	Np	Ate
Athabascan	Apos	Athabascan
Athabascan	Ns	Athabascan
Athabascaner	Acomp	Athabascan
Athabascanest	Asup	Athabascan
Athabascans	Np	Athabascan
Athabaskan	Apos	Athabaskan
Athabaskan	Ns	Athabaskan
Athabaskaner	Acomp	Athabaskan
Athabaskanest	Asup	Athabaskan
Athabaskans	Np	Athabaskan
Athanasian	Apos	Athanasian
Athanasianer	Acomp	Athanasian
Athanasianest	Asup	Athanasian
Athapascan	Apos	Athapascan
Athapascan	Ns	Athapascan
Athapascaner	Acomp	Athapascan
Athapascanest	Asup	Athapascan
Athapascans	Np	Athapascan
Athapaskan	Apos	Athapaskan
Athapaskan	Ns	Athapaskan
Athapaskaner	Acomp	Athapaskan
Athapaskanest	Asup	Athapaskan
Athapaskans	Np	Athapaskan
Athelstan	Ns	Athelstan
Athelstans	Np	Athelstan
Athena	Ns	Athena
Athenas	Np	Athena
Athene	Ns	Athene
Athenes	Np	Athene
Athenian	Apos	Athenian
Athenian	Ns	Athenian
Athenianer	Acomp	Athenian
Athenianest	Asup	Athenian
Athenians	Np	Athenian
Athens	Ns	Athens
Athenses	Np	Athens
Athos	Ns	Athos
Athoss	Np	Athos
Atlanta	Ns	Atlanta
Atlantas	Np	Atlanta
Atlantean	Apos	Atlantean
Atlanteaner	Acomp	Atlantean
Atlanteanest	Asup	Atlantean
Atlantes	Np	Atlantis
Atlantic	Apos	Atlantic
Atlantic	Ns	Atlantic
Atlantic_Ocean	Ns	Atlantic_Ocean
Atlantic_Oceans	Np	Atlantic_Ocean
Atlantic_halibut	Ns	Atlantic_halibut
Atlantic_halibuts	Np	Atlantic_halibut
Atlanticer	Acomp	Atlantic
Atlanticest	Asup	Atlantic
Atlantics	Np	Atlantic
Atlantis	Ns	Atlantis
Atlas	Ns	Atlas
Atlases	Np	Atlas
Atomic_Energy_Commission	Ns	Atomic_Energy_Commission
Atomic_Energy_Commissions	Np	Atomic_Energy_Commission
Atropos	Ns	Atropos
Atroposes	Np	Atropos
Ats	Np	At
Attic	Apos	Attic
Attic	Ns	Attic
Attica	Ns	Attica
Atticas	Np	Attica
Atticer	Acomp	Attic
Atticest	Asup	Attic
Atticise	Vinf|presnot3s	Atticise
Atticised	Vpast	Atticise
Atticised	Vppart	Atticise
Atticises	Vpres3s	Atticise
Atticising	Vprespart	Atticise
Atticism	Ns	Atticism
Atticisms	Np	Atticism
Atticize	Vinf|presnot3s	Atticize
Atticized	Vpast	Atticize
Atticized	Vppart	Atticize
Atticizes	Vpres3s	Atticize
Atticizing	Vprespart	Atticize
Attics	Np	Attic
Attila	Ns	Attila
Attilas	Np	Attila
Au	Ns	Au
Auden	Ns	Auden
Audens	Np	Auden
Audrey_Hepburn	Ns	Audrey_Hepburn
Audrey_Hepburns	Np	Audrey_Hepburn
Audubon_Society	Ns	Audubon_Society
Audubon_Societys	Np	Audubon_Society
Aug	Ns	Aug
Augean	Apos	Augean
Augeanner	Acomp	Augean
Augeannest	Asup	Augean
Augs	Np	Aug
August	Ns	August
Augusta	Ns	Augusta
Augustan	Apos	Augustan
Augustan	Ns	Augustan
Augustaner	Acomp	Augustan
Augustanest	Asup	Augustan
Augustans	Np	Augustan
Augustas	Np	Augusta
Augustine	Ns	Augustine
Augustines	Np	Augustine
Augustinian	Apos	Augustinian
Augustinian	Ns	Augustinian
Augustinianer	Acomp	Augustinian
Augustinianest	Asup	Augustinian
Augustinianism	Ns	Augustinianism
Augustinianisms	Np	Augustinianism
Augustinians	Np	Augustinian
Augustinism	Ns	Augustinism
Augustinisms	Np	Augustinism
Augusts	Np	August
Augustus	Ns	Augustus
Augustuses	Np	Augustus
Aureomycin	Ns	Aureomycin
Aureomycins	Np	Aureomycin
Auriga	Ns	Auriga
Aurigas	Np	Auriga
Aurignacian	Apos	Aurignacian
Aurignacian	Ns	Aurignacian
Aurignacianer	Acomp	Aurignacian
Aurignacianes	Np	Aurignacian
Aurignacianest	Asup	Aurignacian
Aurora	Ns	Aurora
Auroras	Np	Aurora
Aus	Np	Au
Aussie	Ns	Aussie
Aussies	Np	Aussie
Austerlitz	Ns	Austerlitz
Austerlitzes	Np	Austerlitz
Austin	Ns	Austin
Austins	Np	Austin
Australasia	Ns	Australasia
Australasian	Apos	Australasian
Australasian	Ns	Australasian
Australasianer	Acomp	Australasian
Australasianest	Asup	Australasian
Australasians	Np	Australasian
Australasias	Np	Australasia
Australia	Ns	Australia
Australian	Apos	Australian
Australian	Ns	Australian
Australian_Capital_Territory	Ns	Australian_Capital_Territory
Australian_Capital_Territorys	Np	Australian_Capital_Territory
Australian_Rules	Ns	Australian_Rules
Australian_Rules_football	Ns	Australian_Rules_football
Australian_Rules_footballs	Np	Australian_Rules_football
Australian_Ruless	Np	Australian_Rules
Australianer	Acomp	Australian
Australianest	Asup	Australian
Australianism	Ns	Australianism
Australianisms	Np	Australianism
Australianize	Vinf|presnot3s	Australianize
Australianized	Vpast	Australianize
Australianized	Vppart	Australianize
Australianizes	Vpres3s	Australianize
Australianizing	Vprespart	Australianize
Australians	Np	Australian
Australias	Np	Australia
Australoid	Apos	Australoid
Australoid	Ns	Australoid
Australoider	Acomp	Australoid
Australoidest	Asup	Australoid
Australoids	Np	Australoid
Australopithecus	Ns	Australopithecus
Australopithecuses	Np	Australopithecus
Austria	Ns	Austria
Austrian	Apos	Austrian
Austrian	Ns	Austrian
Austrianner	Acomp	Austrian
Austriannest	Asup	Austrian
Austrians	Np	Austrian
Austrias	Np	Austria
Austroasiatic	Apos	Austroasiatic
Austroasiatic	Ns	Austroasiatic
Austroasiaticer	Acomp	Austroasiatic
Austroasiatices	Np	Austroasiatic
Austroasiaticest	Asup	Austroasiatic
Austronesia	Ns	Austronesia
Austronesian	Apos	Austronesian
Austronesian	Ns	Austronesian
Austronesianer	Acomp	Austronesian
Austronesianest	Asup	Austronesian
Austronesians	Np	Austronesian
Austronesias	Np	Austronesia
Autoharp	Ns	Autoharp
Autoharps	Np	Autoharp
Auvergne	Ns	Auvergne
Auvergnes	Np	Auvergne
Av	Ns	Av
Ava_Gardner	Ns	Ava_Gardner
Ava_Gardners	Np	Ava_Gardner
Avalokitesvara	Ns	Avalokitesvara
Avalokitesvaras	Np	Avalokitesvara
Ave	Ns	Ave
Averroism	Ns	Averroism
Averroisms	Np	Averroism
Averroist	Ns	Averroist
Averroistic	Apos	Averroistic
Averroisticer	Acomp	Averroistic
Averroisticest	Asup	Averroistic
Averroists	Np	Averroist
Aves	Np	Ave
Avesta	Ns	Avesta
Avestan	Apos	Avestan
Avestan	Ns	Avestan
Avestaner	Acomp	Avestan
Avestanest	Asup	Avestan
Avestans	Np	Avestan
Avestas	Np	Avesta
Avestic	Apos	Avestic
Avestic	Ns	Avestic
Avesticer	Acomp	Avestic
Avestices	Np	Avestic
Avesticest	Asup	Avestic
Avignon	Ns	Avignon
Avignons	Np	Avignon
Avogadro	Ns	Avogadro
Avogadros	Np	Avogadro
Avs	Np	Av
Axel	Ns	Axel
Axels	Np	Axel
Aymara	Ns	Aymara
Aymaras	Np	Aymara
Ayr	Ns	Ayr
Ayrs	Np	Ayr
Ayrshire	Ns	Ayrshire
Ayrshires	Np	Ayrshire
Azerbaijan	Ns	Azerbaijan
Azerbaijani	Ns	Azerbaijani
