lex2embeds:	trace_lex2_embeds.bg	\
		trace_lex2_embeds.cs	\
		trace_lex2_embeds.da	\
		trace_lex2_embeds.de	\
		trace_lex2_embeds.el	\
		trace_lex2_embeds.en	\
		trace_lex2_embeds.es	\
		trace_lex2_embeds.et	\
		trace_lex2_embeds.fa	\
		trace_lex2_embeds.fr	\
		trace_lex2_embeds.ga	\
		trace_lex2_embeds.hr	\
		trace_lex2_embeds.id	\
		trace_lex2_embeds.it	\
		trace_lex2_embeds.nl	\
		trace_lex2_embeds.no	\
		trace_lex2_embeds.pl	\
		trace_lex2_embeds.pt	\
		trace_lex2_embeds.sl	\
		trace_lex2_embeds.sv

lexembeds:	trace_lex_embeds.ar	\
		trace_lex_embeds.bg	\
		trace_lex_embeds.ca	\
		trace_lex_embeds.cs	\
		trace_lex_embeds.da	\
		trace_lex_embeds.de	\
		trace_lex_embeds.el	\
		trace_lex_embeds.en	\
		trace_lex_embeds.es	\
		trace_lex_embeds.et	\
		trace_lex_embeds.eu	\
		trace_lex_embeds.fi	\
		trace_lex_embeds.fr	\
		trace_lex_embeds.he	\
		trace_lex_embeds.hi	\
		trace_lex_embeds.id	\
		trace_lex_embeds.it	\
		trace_lex_embeds.nl	\
		trace_lex_embeds.no	\
		trace_lex_embeds.pl	\
		trace_lex_embeds.pt	\
		trace_lex_embeds.sl	\
		trace_lex_embeds.sv

lexcoarseembeds:trace_lexcoarse_embeds.ar	\
		trace_lexcoarse_embeds.bg	\
		trace_lexcoarse_embeds.ca	\
		trace_lexcoarse_embeds.cs	\
		trace_lexcoarse_embeds.da	\
		trace_lexcoarse_embeds.de	\
		trace_lexcoarse_embeds.el	\
		trace_lexcoarse_embeds.en	\
		trace_lexcoarse_embeds.es	\
		trace_lexcoarse_embeds.et	\
		trace_lexcoarse_embeds.eu	\
		trace_lexcoarse_embeds.fi	\
		trace_lexcoarse_embeds.fr	\
		trace_lexcoarse_embeds.he	\
		trace_lexcoarse_embeds.hi	\
		trace_lexcoarse_embeds.id	\
		trace_lexcoarse_embeds.it	\
		trace_lexcoarse_embeds.nl	\
		trace_lexcoarse_embeds.no	\
		trace_lexcoarse_embeds.pl	\
		trace_lexcoarse_embeds.pt	\
		trace_lexcoarse_embeds.sl	\
		trace_lexcoarse_embeds.sv

lex2:		trace_lex2.bg	\
		trace_lex2.cs	\
		trace_lex2.da	\
		trace_lex2.de	\
		trace_lex2.el	\
		trace_lex2.en	\
		trace_lex2.es	\
		trace_lex2.et	\
		trace_lex2.fa	\
		trace_lex2.fr	\
		trace_lex2.ga	\
		trace_lex2.hr	\
		trace_lex2.id	\
		trace_lex2.it	\
		trace_lex2.nl	\
		trace_lex2.no	\
		trace_lex2.pl	\
		trace_lex2.pt	\
		trace_lex2.sl	\
		trace_lex2.sv

lex:		trace_lex.ar	\
		trace_lex.bg	\
		trace_lex.ca	\
		trace_lex.cs	\
		trace_lex.da	\
		trace_lex.de	\
		trace_lex.el	\
		trace_lex.en	\
		trace_lex.es	\
		trace_lex.et	\
		trace_lex.eu	\
		trace_lex.fi	\
		trace_lex.fr	\
		trace_lex.he	\
		trace_lex.hi	\
		trace_lex.id	\
		trace_lex.it	\
		trace_lex.nl	\
		trace_lex.no	\
		trace_lex.pl	\
		trace_lex.pt	\
		trace_lex.sl	\
		trace_lex.sv

lexcoarse:	trace_lexcoarse.ar	\
		trace_lexcoarse.bg	\
		trace_lexcoarse.ca	\
		trace_lexcoarse.cs	\
		trace_lexcoarse.da	\
		trace_lexcoarse.de	\
		trace_lexcoarse.el	\
		trace_lexcoarse.en	\
		trace_lexcoarse.es	\
		trace_lexcoarse.et	\
		trace_lexcoarse.eu	\
		trace_lexcoarse.fi	\
		trace_lexcoarse.fr	\
		trace_lexcoarse.he	\
		trace_lexcoarse.hi	\
		trace_lexcoarse.id	\
		trace_lexcoarse.it	\
		trace_lexcoarse.nl	\
		trace_lexcoarse.no	\
		trace_lexcoarse.pl	\
		trace_lexcoarse.pt	\
		trace_lexcoarse.sl	\
		trace_lexcoarse.sv

lex2nochar:	trace_lex2_nochar.bg	\
		trace_lex2_nochar.cs	\
		trace_lex2_nochar.da	\
		trace_lex2_nochar.de	\
		trace_lex2_nochar.el	\
		trace_lex2_nochar.en	\
		trace_lex2_nochar.es	\
		trace_lex2_nochar.et	\
		trace_lex2_nochar.fa	\
		trace_lex2_nochar.fr	\
		trace_lex2_nochar.ga	\
		trace_lex2_nochar.hr	\
		trace_lex2_nochar.id	\
		trace_lex2_nochar.it	\
		trace_lex2_nochar.nl	\
		trace_lex2_nochar.no	\
		trace_lex2_nochar.pl	\
		trace_lex2_nochar.pt	\
		trace_lex2_nochar.sl	\
		trace_lex2_nochar.sv	\
		trace_lex2_nochar.gl	\
		trace_lex2_nochar.grc	\
		trace_lex2_nochar.hu	\
		trace_lex2_nochar.la	\
		trace_lex2_nochar.ro

smalltarget:	trace_lex2_nochar.no	\
		trace_lex2_nochar.pl	\
		trace_lex2_nochar.pt


lexnochar:	trace_lex_nochar.ar	\
		trace_lex_nochar.bg	\
		trace_lex_nochar.ca	\
		trace_lex_nochar.cs	\
		trace_lex_nochar.da	\
		trace_lex_nochar.de	\
		trace_lex_nochar.el	\
		trace_lex_nochar.en	\
		trace_lex_nochar.es	\
		trace_lex_nochar.et	\
		trace_lex_nochar.eu	\
		trace_lex_nochar.fi	\
		trace_lex_nochar.fr	\
		trace_lex_nochar.he	\
		trace_lex_nochar.hi	\
		trace_lex_nochar.id	\
		trace_lex_nochar.it	\
		trace_lex_nochar.nl	\
		trace_lex_nochar.no	\
		trace_lex_nochar.pl	\
		trace_lex_nochar.pt	\
		trace_lex_nochar.sl	\
		trace_lex_nochar.sv

lexcoarsenochar:trace_lexcoarse_nochar.ar	\
		trace_lexcoarse_nochar.bg	\
		trace_lexcoarse_nochar.ca	\
		trace_lexcoarse_nochar.cs	\
		trace_lexcoarse_nochar.da	\
		trace_lexcoarse_nochar.de	\
		trace_lexcoarse_nochar.el	\
		trace_lexcoarse_nochar.en	\
		trace_lexcoarse_nochar.es	\
		trace_lexcoarse_nochar.et	\
		trace_lexcoarse_nochar.eu	\
		trace_lexcoarse_nochar.fi	\
		trace_lexcoarse_nochar.fr	\
		trace_lexcoarse_nochar.he	\
		trace_lexcoarse_nochar.hi	\
		trace_lexcoarse_nochar.id	\
		trace_lexcoarse_nochar.it	\
		trace_lexcoarse_nochar.nl	\
		trace_lexcoarse_nochar.no	\
		trace_lexcoarse_nochar.pl	\
		trace_lexcoarse_nochar.pt	\
		trace_lexcoarse_nochar.sl	\
		trace_lexcoarse_nochar.sv

lex2b:		trace_lex2.gl	\
		trace_lex2.grc	\
		trace_lex2.hu	\
		trace_lex2.la	\
		trace_lex2.ro

lexb:		trace_lex.gl	\
		trace_lex.hu	\
		trace_lex.kk	\
		trace_lex.lv	\
		trace_lex.ro	\
		trace_lex.ru	\
		trace_lex.tr	\
		trace_lex.zh

lexcoarseb:	trace_lexcoarse.gl	\
		trace_lexcoarse.hu	\
		trace_lexcoarse.kk	\
		trace_lexcoarse.lv	\
		trace_lexcoarse.ro	\
		trace_lexcoarse.ru	\
		trace_lexcoarse.tr	\
		trace_lexcoarse.zh

lexbnochar:	trace_lex_nochar.gl	\
		trace_lex_nochar.hu	\
		trace_lex_nochar.kk	\
		trace_lex_nochar.lv	\
		trace_lex_nochar.ro	\
		trace_lex_nochar.ru	\
		trace_lex_nochar.tr	\
		trace_lex_nochar.zh

lexcoarsebnochar:trace_lexcoarse_nochar.gl	\
		trace_lexcoarse_nochar.hu	\
		trace_lexcoarse_nochar.kk	\
		trace_lexcoarse_nochar.lv	\
		trace_lexcoarse_nochar.ro	\
		trace_lexcoarse_nochar.ru	\
		trace_lexcoarse_nochar.tr	\
		trace_lexcoarse_nochar.zh

baselinenochar:	trace_nolex_nochar.ar	\
		trace_nolex_nochar.bg	\
		trace_nolex_nochar.ca	\
		trace_nolex_nochar.cs	\
		trace_nolex_nochar.da	\
		trace_nolex_nochar.de	\
		trace_nolex_nochar.el	\
		trace_nolex_nochar.en	\
		trace_nolex_nochar.es	\
		trace_nolex_nochar.et	\
		trace_nolex_nochar.eu	\
		trace_nolex_nochar.fa	\
		trace_nolex_nochar.fi	\
		trace_nolex_nochar.fr	\
		trace_nolex_nochar.ga	\
		trace_nolex_nochar.gl	\
		trace_nolex_nochar.grc	\
		trace_nolex_nochar.he	\
		trace_nolex_nochar.hi	\
		trace_nolex_nochar.hr	\
		trace_nolex_nochar.hu	\
		trace_nolex_nochar.id	\
		trace_nolex_nochar.it	\
		trace_nolex_nochar.kk	\
		trace_nolex_nochar.la	\
		trace_nolex_nochar.lv	\
		trace_nolex_nochar.nl	\
		trace_nolex_nochar.no	\
		trace_nolex_nochar.pl	\
		trace_nolex_nochar.pt	\
		trace_nolex_nochar.ro	\
		trace_nolex_nochar.ru	\
		trace_nolex_nochar.sl	\
		trace_nolex_nochar.sv	\
		trace_nolex_nochar.tr	\
		trace_nolex_nochar.zh

baseline:	trace_nolex.ar	\
		trace_nolex.bg	\
		trace_nolex.ca	\
		trace_nolex.cs	\
		trace_nolex.da	\
		trace_nolex.de	\
		trace_nolex.el	\
		trace_nolex.en	\
		trace_nolex.es	\
		trace_nolex.et	\
		trace_nolex.eu	\
		trace_nolex.fa	\
		trace_nolex.fi	\
		trace_nolex.fr	\
		trace_nolex.ga	\
		trace_nolex.gl	\
		trace_nolex.grc	\
		trace_nolex.he	\
		trace_nolex.hi	\
		trace_nolex.hr	\
		trace_nolex.hu	\
		trace_nolex.id	\
		trace_nolex.it	\
		trace_nolex.kk	\
		trace_nolex.la	\
		trace_nolex.lv	\
		trace_nolex.nl	\
		trace_nolex.no	\
		trace_nolex.pl	\
		trace_nolex.pt	\
		trace_nolex.ro	\
		trace_nolex.ru	\
		trace_nolex.sl	\
		trace_nolex.sv	\
		trace_nolex.tr	\
		trace_nolex.zh

baselineembeds:	trace_nolex_embeds.ar	\
		trace_nolex_embeds.bg	\
		trace_nolex_embeds.ca	\
		trace_nolex_embeds.cs	\
		trace_nolex_embeds.da	\
		trace_nolex_embeds.de	\
		trace_nolex_embeds.el	\
		trace_nolex_embeds.en	\
		trace_nolex_embeds.es	\
		trace_nolex_embeds.et	\
		trace_nolex_embeds.eu	\
		trace_nolex_embeds.fa	\
		trace_nolex_embeds.fi	\
		trace_nolex_embeds.fr	\
		trace_nolex_embeds.ga	\
		trace_nolex_embeds.he	\
		trace_nolex_embeds.hi	\
		trace_nolex_embeds.hr	\
		trace_nolex_embeds.id	\
		trace_nolex_embeds.it	\
		trace_nolex_embeds.nl	\
		trace_nolex_embeds.no	\
		trace_nolex_embeds.pl	\
		trace_nolex_embeds.pt	\
		trace_nolex_embeds.sl	\
		trace_nolex_embeds.sv


speedup:	trace_lex_embeds.ar	\
		trace_lex_embeds.ca	\
		trace_lex_embeds.de	\
		trace_lex_embeds.es	\
		trace_lex_embeds.et	\
		trace_lex_embeds.fi	\
		trace_lex_embeds.fr	\
		trace_lex_embeds.he	\
		trace_lex_embeds.hi	\
		trace_lex_embeds.id	\
		trace_lex_embeds.it	\
		trace_lex_embeds.nl	\
		trace_lex_embeds.no	\
		trace_lex_embeds.pl	\
		trace_lex_embeds.pt	\
		trace_lex_embeds.sl	\
		trace_lex_embeds.sv

csspeedup:	trace_lex_embeds.cs		\
		trace_lex2_embeds.cs		\
		trace_lexcoarse_embeds.cs	\
		trace_lex.cs			\
		trace_lex2.cs			\
		trace_lexcoarse.cs		\
		trace_lex_nolex.cs		\
		trace_lex2_nolex.cs		\
		trace_lexcoarse_nolex.cs

allnochar: lexnochar lex2nochar lexcoarsenochar lexbnochar lex2bnochar lexcoarsebnochar

infos:
	echo "python = "`which python` > infos.$$$$;\
	echo "PATH = " ${PATH} >> infos.$$$$


trace_lex2_embeds.%:
	python run_lex2_embeds.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_lex_embeds.%:
	python run_lex_embeds.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_lexcoarse_embeds.%:
	python run_lexcoarse_embeds.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_lex2.%:
	python run_simple_lex2.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_lex.%:
	python run_simple_lex.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_lexcoarse.%:
	python run_simple_lexcoarse.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_lex2_nochar.%:
	python run_simple_nochar_lex2.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_lex_nochar.%:
	python run_simple_nochar_lex.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_lexcoarse_nochar.%:
	python run_simple_nochar_lexcoarse.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_nolex_nochar.%:
	python run_simple_nochars.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_nolex.%:
	python run_simple.py --dynet-seed 113 --lang $* > $@ 2>&1

trace_nolex_embeds.%:
	python run_simple_embeds.py --dynet-seed 113 --lang $* > $@ 2>&1

